version: '3'
services:
  finance1:
    image: crpi-d8fe432ldlewt4lj.cn-chengdu.personal.cr.aliyuncs.com/myprefer/finance:1.1.0
    network_mode: host  # 使用宿主机的网络
    # 启动
    command: >
      bash -c "echo MYSQL_USER=finance > /app/.env &&
               echo MYSQL_PASSWORD=79sdiubfhsiojeio3 >> /app/.env &&
               echo MYSQL_HOST=8.152.214.0 >> /app/.env &&
               echo MYSQL_PORT=3306 >> /app/.env &&
               echo MYSQL_DB=finance >> /app/.env &&
               echo CACHE_HOST=8.152.214.0 >> /app/.env &&
               echo CACHE_PORT=6379 >> /app/.env &&
               echo CACHE_DB=0 >> /app/.env &&
               echo FASTAPI_PORT=8000 >> /app/.env &&
               exec python main.py"